1:56:2:dig2:Warn:DEBUG MODE ON. Can be slow !
1:56:3:alg:Info:analyze ./programs/hola/03.dig.c
1:56:3:alg:Info:set seed to: 1493794562.28 (test 43)
1:56:3:alg:Info:check reachability
1:56:3:alg:Info:gen eqts at 1 locs: l20 (int i, int k, int n, int l, int t)
Traceback (most recent call last):
  File "dig2.py", line 71, in <module>
    doEqts=not args.noeqts, doIeqs=not args.noieqs)
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 406, in start
    if doEqts: _gen('eqts')
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 399, in _gen
    invs = solver.gen(deg, traces, inps)
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 193, in gen
    initrs = [self.getInitTraces(loc, deg, traces, inps) for loc in traces]
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 123, in getInitTraces
    newTraces = self.getTracesAndUpdate(newInps, traces)
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 68, in getTracesAndUpdate
    assert inps
AssertionError
