2:47:29:dig2:Warn:DEBUG MODE ON. Can be slow !
2:47:30:alg:Info:analyze ./programs/hola/22.dig.c
2:47:30:alg:Info:set seed to: 1493797649.89 (test 19)
2:47:30:alg:Info:check reachability
2:47:31:alg:Info:gen eqts at 1 locs: l21 (int x, int y, int z)
2:47:40:alg:Info:2 invs:
l21: y - z == 0, x - z == 0
2:47:40:alg:Info:gen ieqs at 1 locs: l21 (int x, int y, int z)
2:47:40:alg:Info:1 locs: check upperbounds for 18 terms
Traceback (most recent call last):
  File "dig2.py", line 71, in <module>
    doEqts=not args.noeqts, doIeqs=not args.noieqs)
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 407, in start
    if doIeqs: _gen('ieqs')        
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 399, in _gen
    invs = solver.gen(deg, traces, inps)
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 252, in gen
    _ = self.getTracesAndUpdate(newInps, traces)
  File "/home/tnguyen/Dropbox/git/dig2/alg.py", line 68, in getTracesAndUpdate
    assert inps
AssertionError
